apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-api-config
  namespace: blog
data:
  SPRING_PROFILES_ACTIVE: kubernetes

  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/blogdb
  SPRING_DATASOURCE_USERNAME: bloguser

  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
