apiVersion: v1
kind: Secret
metadata:
  name: blog-api-secret
  namespace: blog
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: bloguser
  SPRING_DATASOURCE_PASSWORD: blogpass
  JWT_SECRET: blog_api_jwt_secret_2025_azure_k8s_secure_key_987654321
  JWT_EXPIRATION_MS: "3600000"
