apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress
  namespace: blog
spec:
  ingressClassName: webapprouting.kubernetes.azure.com

  tls:
  - hosts:
    - omni-mark-10.centralindia.aksapp.io
    secretName: aks-managed-tls

  rules:
  - host: omni-mark-10.centralindia.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blog-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: blog-api
            port:
              number: 8080
