apiVersion: v1
kind: Pod
metadata:
  name: mysql-reset
  namespace: blog
spec:
  restartPolicy: Never
  containers:
    - name: mysql
      image: mysql:8.0
      command: ["mysqld"]
      args:
        - "--skip-grant-tables"
        - "--skip-networking=0"
      volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-storage
      persistentVolumeClaim:
        claimName: mysql-pvc
