apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: blog
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: Ashu1495@
  MYSQL_DATABASE: blogdb
  MYSQL_USER: bloguser
  MYSQL_PASSWORD: blogpass
